In [1]:
import numpy as np
import pandas as pd
import re
import matplotlib.pyplot as plt
from scipy.spatial.distance import pdist, squareform
from src.data_processing import get_recipe_df, mean_scale_recipes, drop_uncommon_ingreds
from pymongo import MongoClient
from src.recipe_distance import *

In [2]:
client = MongoClient()
db = client['recipes']
coll = db.eda_cookies

cookie_regx = re.compile("cookie", re.IGNORECASE)

In [3]:
df_cookies = get_recipe_df(coll, cookie_regx)

In [40]:
df_scaled = mean_scale_recipes(df_cookies)

In [43]:
df_reduced = drop_uncommon_ingreds(df_scaled, 20)

In [44]:
df_reduced.shape

(2488, 102)

In [45]:
df_scaled.shape

(2488, 245)

In [34]:
df_binary = df_reduced>0

In [36]:
df_binary.head().T

url                 http://www.seriouseats.com/recipes/2010/02/the-best-chocolate-chip-cookies-kumiko-recipe-20100201.html  \
allspic                                                         False                                                        
almond                                                          False                                                        
almond extract                                                  False                                                        
almond flour                                                    False                                                        
almond meal                                                     False                                                        
appl                                                            False                                                        
applesauc                                                       False                                                        
apricot                                                         False                                                        
bacon                                                           False                                                        
bake powder                                                      True                                                        
bake soda                                                        True                                                        
banana                                                          False                                                        
bittersweet chocol                                               True                                                        
black pepper                                                    False                                                        
brown sugar                                                      True                                                        
butter                                                           True                                                        
canola oil                                                      False                                                        
cardamom                                                        False                                                        
carrot                                                          False                                                        
cayenn pepper                                                   False                                                        
cherri                                                          False                                                        
chocol                                                          False                                                        
cinnamon                                                        False                                                        
clove                                                           False                                                        
cocoa                                                           False                                                        
cocoa powder                                                    False                                                        
coconut                                                         False                                                        
coconut oil                                                     False                                                        
coffe                                                           False                                                        
confection sugar                                                False                                                        
...                                                               ...                         

In [47]:
pdist(df_reduced, metric='cosine')

array([ 0.34384383,  0.55835529,  0.3471587 , ...,  0.52642452,
        0.6312994 ,  0.53389407])

In [22]:
pair_dist_composite(df, ratio=0)

array([[ 0.        ,  0.46153846,  0.46153846, ...,  0.5625    ,
         0.4       ,  0.625     ],
       [ 0.46153846,  0.        ,  0.57142857, ...,  0.46666667,
         0.58823529,  0.625     ],
       [ 0.46153846,  0.57142857,  0.        , ...,  0.64705882,
         0.58823529,  0.70588235],
       ..., 
       [ 0.5625    ,  0.46666667,  0.64705882, ...,  0.        ,
         0.41176471,  0.61111111],
       [ 0.4       ,  0.58823529,  0.58823529, ...,  0.41176471,
         0.        ,  0.55555556],
       [ 0.625     ,  0.625     ,  0.70588235, ...,  0.61111111,
         0.55555556,  0.        ]])

In [7]:
jac_dist = recipe_jaccard_pairs(df>1)

In [9]:
jac_dist

array([ 0.8       ,  1.        ,  1.        , ...,  0.83333333,
        1.        ,  1.        ])

In [17]:
cos_dist = pdist(df, metric='cosine')

In [18]:
cos_dist

array([ 0.34384383,  0.55835529,  0.3471587 , ...,  0.52642452,
        0.6312994 ,  0.53389407])

In [58]:
squareform(jac_dist+cos_dist)/2

array([[ 0.        ,  0.57192192,  0.77917765, ...,  0.64751984,
         0.67962082,  0.78512239],
       [ 0.57192192,  0.        ,  0.6862546 , ...,  0.77396493,
         0.82883922,  0.83740267],
       [ 0.77917765,  0.6862546 ,  0.        , ...,  0.78078046,
         0.65282216,  0.84704403],
       ..., 
       [ 0.64751984,  0.77396493,  0.78078046, ...,  0.        ,
         0.67987892,  0.8156497 ],
       [ 0.67962082,  0.82883922,  0.65282216, ...,  0.67987892,
         0.        ,  0.76694703],
       [ 0.78512239,  0.83740267,  0.84704403, ...,  0.8156497 ,
         0.76694703,  0.        ]])

In [13]:
df = mean_scale_recipes(drop_uncommon_ingreds(df_cookies, 30))

In [16]:
df.describe().T

count      mean       std  min       25%       50%  \
allspic             2488.0  0.022508  0.199072  0.0  0.000000  0.000000   
almond              2488.0  0.071543  0.348000  0.0  0.000000  0.000000   
almond extract      2488.0  0.036174  0.335252  0.0  0.000000  0.000000   
appl                2488.0  0.014469  0.146928  0.0  0.000000  0.000000   
applesauc           2488.0  0.019695  0.155483  0.0  0.000000  0.000000   
bacon               2488.0  0.017283  0.152562  0.0  0.000000  0.000000   
bake powder         2488.0  0.327170  0.615299  0.0  0.000000  0.000000   
bake soda           2488.0  0.493971  0.667205  0.0  0.000000  0.000000   
banana              2488.0  0.020096  0.166971  0.0  0.000000  0.000000   
bittersweet chocol  2488.0  0.054260  0.269702  0.0  0.000000  0.000000   
black pepper        2488.0  0.018489  0.197721  0.0  0.000000  0.000000   
brown sugar         2488.0  0.449759  0.599979  0.0  0.000000  0.000000   
butter              2488.0  0.801447  0.580421  0.0  0.354620  0.820692   
canola oil          2488.0  0.028939  0.193416  0.0  0.000000  0.000000   
cardamom            2488.0  0.021302  0.202955  0.0  0.000000  0.000000   
cherri              2488.0  0.021704  0.160503  0.0  0.000000  0.000000   
chocol              2488.0  0.112138  0.396513  0.0  0.000000  0.000000   
cinnamon            2488.0  0.229904  3.134047  0.0  0.000000  0.000000   
clove               2488.0  0.065113  0.341203  0.0  0.000000  0.000000   
cocoa               2488.0  0.030145  0.201506  0.0  0.000000  0.000000   
cocoa powder        2488.0  0.095257  0.350228  0.0  0.000000  0.000000   
coconut             2488.0  0.042203  0.328459  0.0  0.000000  0.000000   
coconut oil         2488.0  0.016479  0.164441  0.0  0.000000  0.000000   
confection sugar    2488.0  0.110932  0.392628  0.0  0.000000  0.000000   
cook spray          2488.0  0.018489  0.136041  0.0  0.000000  0.000000   
corn syrup          2488.0  0.027733  0.230243  0.0  0.000000  0.000000   
cornstarch          2488.0  0.018891  0.207725  0.0  0.000000  0.000000   
cranberri           2488.0  0.033360  0.203455  0.0  0.000000  0.000000   
cream chees         2488.0  0.038585  0.223867  0.0  0.000000  0.000000   
cream tartar        2488.0  0.013264  0.137572  0.0  0.000000  0.000000   
...                    ...       ...       ...  ...       ...       ...   
orang zest          2488.0  0.025723  0.452947  0.0  0.000000  0.000000   
peanut              2488.0  0.013264  0.144713  0.0  0.000000  0.000000   
peanut butter       2488.0  0.088023  0.337243  0.0  0.000000  0.000000   
pecan               2488.0  0.051045  0.263121  0.0  0.000000  0.000000   
pistachio           2488.0  0.013666  0.143435  0.0  0.000000  0.000000   
powder sugar        2488.0  0.084003  0.364053  0.0  0.000000  0.000000   
pumpkin             2488.0  0.017283  0.142459  0.0  0.000000  0.000000   
raisin              2488.0  0.067926  0.283792  0.0  0.000000  0.000000   
raspberri jam       2488.0  0.014871  0.133736  0.0  0.000000  0.000000   
rice flour          2488.0  0.012862  0.137278  0.0  0.000000  0.000000   
salt                2488.0  0.774116  3.564346  0.0  0.147888  0.401471   
seed                2488.0  0.022508  0.257076  0.0  0.000000  0.000000   
semi sweet chocol   2488.0  0.038987  0.219370  0.0  0.000000  0.000000   
semisweet chocol    2488.0  0.098473  0.336380  0.0  0.000000  0.000000   
shorten             2488.0  0.034968  0.210676  0.0  0.000000  0.000000   
sugar               2488.0  0.739148  0.699382  0.0  0.000000  0.648451   
toffe               2488.0  0.017685  0.150860  0.0  0.000000  0.000000   
unsweeten chocol    2488.0  0.019293  0.163365  0.0  0.000000  0.000000   
vanilla             2488.0  0.143891  1.420077  0.0  0.000000  0.000000   
vanilla bean        2488.0  0.016077  0.561274  0.0  0.000000  0.000000   
vanilla extract     2488.0  0.532154  0.735973  0.0  0.000000  0.338549   
veget oil           2488.0  0.027331  0.212598